name: danuras_web_service_editor
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dotted_border: ^2.1.0
  file_picker: ^5.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_widget_from_html: ^0.14.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_editor_enhanced: ^2.5.1
  http: ^0.13.6
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/kerangka/
    - assets/images/kerangka/advantage/
    - assets/images/kerangka/blog/
    - assets/images/kerangka/card/
    - assets/images/kerangka/card/content/
    - assets/images/kerangka/footer/
    - assets/images/kerangka/header/
    - assets/images/kerangka/location/
    - assets/images/kerangka/testimony/
